apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: icap
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.1-192.168.1.10

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
   - icap