apiVersion: purelb.io/v1
kind: ServiceGroup
metadata:
  name: default
  namespace: purelb
spec:
  local:
    v4pools:
    - subnet: 191.168.1.0/24
      pool: 192.168.1.1-192.168.1.10
      aggregation: default
